name: Cleanup Dangling Docker Images

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:       # Allows manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Remove dangling Docker images (tagged <none>)
        run: |
          echo "Removing dangling Docker images..."
          sudo docker images -f "dangling=true" -q | sudo xargs -r docker rmi || echo "No dangling images to remove"
